[build]
  publish = "_site"
  command = "npm run build"
  functions = "netlify/functions"
  port = 8888              # Porten du vil besøke i nettleseren
  targetPort = 8080        # Porten 11ty faktisk kjører på
  framework = "#custom" # Forteller Netlify at vi styrer oppsettet selv
  delay = 3000          # Venter 3 sekunder før den prøver å koble til